apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kafka.fullname" . }}-pdb
spec:
  selector:
    matchLabels:
      {{- include "kafka.selectorLabels" . | nindent 6 }}
  maxUnavailable: 1
