# Default values for zookeeper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

########## REPLICA SETTING ##########
# replicas must be in odd number and 3 or 5 is the best.
# not needed more than 5
replicaCount: 3

########## CONTAINER IMAGE SETTING ##########
images:
  registry: "sparkandassociates"  # docker hub
  # pullPolicy: "IfNotPresent"
  pullPolicy: "Always"
  ## zookeeper image setting
  zookeeper:
    name: "zookeeper-spark"
    tag: "3.6.3"
  ## node exporter image setting
  nodeExporter:
    name: "node_exporter-spark"
    tag: "latest"

imagePullSecrets: #[]
  - name: "bccard-dockerhub-sparkandassociates"
nameOverride: "spark"
fullnameOverride: "" #"myd-zookeeper01"

########## EXECUTION SETTING ##########
configs:
  ## node exporter port number. comment out this settings if not use node exporter
  nodeExporter: #{}
    port: 9100
  ## storage volume request
  volume:
    storage: "10Gi"
    storageClass: ""
  ## zookeeper container variables
  ## refer the administrators' documents for Apache ZooKeeper
  optional: #[]
    ## for sasl authentication.
    - name: ZOO_AUTH_PROVIDER__1
      value: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
    - name: ZOO_AUTH_PROVIDER__2
      value: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
    - name: ZOO_AUTH_PROVIDER__3
      value: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
    ## security settings for zookeeper-spark
    - name: SZOO_SERVERAUTH_SASL_MD5_ENABLE
      value: "true"
    - name: SZOO_SERVERAUTH_USER
      value: zookeeper
    - name: SZOO_SERVERAUTH_PASS
      value: zookeeper01
    - name: SZOO_CLIENTAUTH_SASL_MD5_ENABLE
      value: "true"
    - name: SZOO_CLIENTAUTH_USERS
      value: user_kafka="kafka01" user_zookeeper="zookeeper01" user_super="super_zookeeper01";
    ## jvm settings
    - name: ZK_SERVER_HEAP
      value: "1000"
    # - name: JMXPORT
    #   value: "2099"

########## K8S SERVICE SETTING ##########
## should match port number to container
service:
  type: ClusterIP
  port: 2181

########## K8S RESOURCE SETTING ##########
resources: #{}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: "250m"
    memory: "128Mi"

########## K8S AUTOSCALE SETTING : MUST DISABLE ##########
autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

########## OTHER SETTING ##########
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 5555

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  runAsUser: 1000100001

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

affinity: {}
