apiVersion: v1
kind: Service
metadata:
  name: {{ include "felice.fullname" . }}-cs
  labels:
    {{- include "felice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: felice-front
    port: 8080
  - name: felice-mon
    port: 9090
  - name: felice-board
    port: 3000
  selector:
    {{- include "felice.selectorLabels" . | nindent 4 }}
